apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Disable protected mode
    protected-mode no
    # Set a password for Redis
    requirepass your_redis_password_here
